

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    depends_on:
      - postgres
    networks:
      - app_network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
     - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - ./src/web/database/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
     - app_network 
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
 postgres_data:



