[project]
name = "projet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "haystack-ai>=2.12.2",
    "huggingface-hub>=0.30.2",
    "pandas>=2.2.3",
    "python-dotenv>=1.1.0",
]
